### ISSUE TITLE
Center content

### ISSUE THREAD

**Issue by martoio** [joyy1/teacozy#2]
You can use:
```css
.container{
   margin: 0 auto;
}
```
to center your container. Here's an example: https://codepen.io/anon/pen/drNKYe
